### ISSUE TITLE
大大，机器人发送图片的时候一直报错

### ISSUE THREAD

**Issue by rickiy1ws** [GardenHamster/Theresa3rd-Bot#10]
![报错1](https://user-images.githubusercontent.com/95345096/195882832-a7b40edf-bc08-4857-9b1b-87c33fd52046.jpg)
![报错2](https://user-images.githubusercontent.com/95345096/195883129-4a9b8fc8-e2c4-4a09-a28e-6d8bda45b109.jpg)
cookie已经更新过了
[[这里是日志的内容]]
2022-10-14 23:05:54,691 [3] ERROR RollingLog [(null)] - sendGeneralLolisukiImageAsync群消息发送失败
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.InternalUploadPictureAsync(InternalSessionInfo session, UploadTarget type, Stream imgStream, Boolean disposeStream, CancellationToken token)
   at Theresa3rd_Bot.Handler.LolisukiHandler.sendGeneralLolisukiImageAsync(IMiraiHttpSession session, IGroupMessageEventArgs args, String message) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Handler\LolisukiHandler.cs:line 97

2022-10-14 23:05:56,063 [3] ERROR RollingLog [(null)] - sendGeneralLolisukiImageAsync异常
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.InternalUploadPictureAsync(InternalSessionInfo session, UploadTarget type, Stream imgStream, Boolean disposeStream, CancellationToken token)
   at Theresa3rd_Bot.Handler.LolisukiHandler.sendGeneralLolisukiImageAsync(IMiraiHttpSession session, IGroupMessageEventArgs args, String message) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Handler\LolisukiHandler.cs:line 97

**Comment by GardenHamster** [comment]
https://github.com/GardenHamster/Theresa3rd-Bot/issues/11
