### ISSUE TITLE
bot发送图片失败且报错

### ISSUE THREAD

**Issue by anucan** [GardenHamster/Theresa3rd-Bot#11]
版本：mcl 2.1.1
mcl-api-https: 2.5.2
JDK 11
Theresa-Bot: 0.7.2
日志文件如下：
2022-10-15 07:06:20,502 [22] ERROR RollingLog [(null)] - sendGeneralPixivImageAsync群消息发送失败
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.InternalUploadPictureAsync(InternalSessionInfo session, UploadTarget type, Stream imgStream, Boolean disposeStream, CancellationToken token)
   at Theresa3rd_Bot.Handler.PixivHandler.sendGeneralPixivImageAsync(IMiraiHttpSession session, IGroupMessageEventArgs args, String message) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Handler\PixivHandler.cs:line 138

2022-10-15 07:06:21,903 [22] ERROR RollingLog [(null)] - sendGeneralPixivImageAsync异常
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.InternalUploadPictureAsync(InternalSessionInfo session, UploadTarget type, Stream imgStream, Boolean disposeStream, CancellationToken token)
   at Theresa3rd_Bot.Handler.PixivHandler.sendGeneralPixivImageAsync(IMiraiHttpSession session, IGroupMessageEventArgs args, String message) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Handler\PixivHandler.cs:line 138

**Comment by HaranoShirone** [comment]
这边出现了同样的错误

**Comment by GardenHamster** [comment]
i.pixiv.re和i.pixiv.nl两个代理挂了，需要换一下代理，或者直接关掉代理用梯子下载图片

**Comment by anucan** [comment]
好的谢谢

**Comment by GardenHamster** [comment]
gc酱的pixiv代理，https://mirai.mamoe.net/topic/1322/rs-pixiv-%E6%98%93%E4%BA%8E%E6%90%AD%E5%BB%BA%E7%9A%84pixiv%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1

**Comment by anucan** [comment]
好的谢谢推荐，大佬辛苦了

**Comment by GardenHamster** [comment]
或者botsettings.yml里面改一下这两行
PixivFreeProxy:false
PixivImgProxy: ''
