### ISSUE TITLE
订阅画师或标签后，获取pixiv作品信息失败的两种报错

### ISSUE THREAD

**Issue by holygodly** [GardenHamster/Theresa3rd-Bot#21]
在更新某画师的画时，大概有60%的概率会出现“The SSL connection could not be established, see inner exception.”或者“The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.”的报错。机器人架在服务器上，服务器我挂了代理，使用的也是代理的端口（搜图啥的都没多大问题）
![image](https://user-images.githubusercontent.com/41179861/216090138-9545d3cc-4f2c-4c9e-8465-425cd48c4dec.png)
同时订阅标签过段时间大概100%都会报错。报错内容如下：
Theresa3rd_Bot.Exceptions.BaseException: 搜索pixiv标签黑丝失败
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Theresa3rd_Bot.Util.HttpHelper.GetWithProxyAsync(String url, Dictionary`2 headerDic, Int32 timeout) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\HttpHelper.cs:line 83
   at Theresa3rd_Bot.Util.PixivHelper.GetPixivAsync(String url, Dictionary`2 headerDic, Int32 timeout) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\PixivHelper.cs:line 183
   at Theresa3rd_Bot.Util.PixivHelper.GetPixivSearchAsync(String keyword, Int32 pageNo, Boolean isMatchAll, Boolean includeR18) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\PixivHelper.cs:line 57
   --- End of inner exception stack trace ---
   at Theresa3rd_Bot.Util.PixivHelper.GetPixivSearchAsync(String keyword, Int32 pageNo, Boolean isMatchAll, Boolean includeR18) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\PixivHelper.cs:line 63
   at Theresa3rd_Bot.Business.PixivBusiness.getRandomWorkAsync(String tagNames, Boolean includeR18) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Business\PixivBusiness.cs:line 209
   at Theresa3rd_Bot.Business.PixivBusiness.getRandomWorkInTagsAsync(Boolean includeR18) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Business\PixivBusiness.cs:line 72
   at Theresa3rd_Bot.Handler.PixivHandler.sendGeneralPixivImageAsync(IMiraiHttpSession session, IGroupMessageEventArgs args, String message) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Handler\PixivHandler.cs:line 77
还有一种是：
2023-02-01 18:01:52,858 [27] ERROR RollingLog [(null)] - 推送pixiv用户[16731]订阅时异常
Theresa3rd_Bot.Exceptions.BaseException: 获取pixiv画师16731作品列表失败
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Theresa3rd_Bot.Util.HttpHelper.GetWithProxyAsync(String url, Dictionary`2 headerDic, Int32 timeout) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\HttpHelper.cs:line 86
   at Theresa3rd_Bot.Util.PixivHelper.GetPixivAsync(String url, Dictionary`2 headerDic, Int32 timeout) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\PixivHelper.cs:line 189
   at Theresa3rd_Bot.Util.PixivHelper.GetPixivUserInfoAsync(String userId) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\PixivHelper.cs:line 93
   --- End of inner exception stack trace ---
   at Theresa3rd_Bot.Util.PixivHelper.GetPixivUserInfoAsync(String userId) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\PixivHelper.cs:line 99
   at Theresa3rd_Bot.Business.PixivBusiness.getPixivUserSubscribeAsync(SubscribeTask subscribeTask, Int32 getCount) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Business\PixivBusiness.cs:line 417
   at Theresa3rd_Bot.Timer.PixivUserTimer.SendWithSubscribe(PixivBusiness pixivBusiness) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Timer\PixivUserTimer.cs:line 74

**Comment by holygodly** [comment]
总体来说大佬的机器人还是很好用的，群里的小儿子们都很开心哈哈哈哈

**Comment by GardenHamster** [comment]
感谢支持

**Comment by GardenHamster** [comment]
先看看服务器上能不能登录P站，如果可以的话将PixivHttpProxy改为''试试，改完记得重启bot
