### ISSUE TITLE
下载图片失败

### ISSUE THREAD

**Issue by KaRuiqin** [GardenHamster/Theresa3rd-Bot#22]
ERROR RollingLog [(null)] - PixivBusiness.downImg下载图片失败
System.Net.Http.HttpRequestException: Response status code does not indicate success: 522 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Theresa3rd_Bot.Util.HttpHelper.DownFileAsync(String imgUrl, String fullImageSavePath, Dictionary`2 headerDic, Int32 timeout) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\HttpHelper.cs:line 193
   at Theresa3rd_Bot.Business.SetuBusiness.downImgAsync(String pixivId, String originUrl, Boolean isGif) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Business\SetuBusiness.cs:line 49

所有图床都无法下载且服务器可以正常访问
这个问题有一段时间了，之前一直是正常运行。

**Comment by GardenHamster** [comment]
检查一下配置文件里面有没有pixiv.lolisuki.cn这个代理，有的话将它清除，这个代理已经关掉了

**Comment by KaRuiqin** [comment]
哦原来是这样
我的问题已解决，谢谢大佬 >_<
