### ISSUE TITLE
无法下载图片是什么情况

### ISSUE THREAD

**Issue by shouweiwangzhe** [GardenHamster/Theresa3rd-Bot#23]
2023-02-11 14:50:40,991 [13] ERROR RollingLog [(null)] - PixivBusiness.downImg下载图片失败
System.Net.Http.HttpRequestException: Response status code does not indicate success: 522 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Theresa3rd_Bot.Util.HttpHelper.DownFileAsync(String imgUrl, String fullImageSavePath, Dictionary`2 headerDic, Int32 timeout) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Util\HttpHelper.cs:line 193
   at Theresa3rd_Bot.Business.SetuBusiness.downImgAsync(String pixivId, String originUrl, Boolean isGif) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Business\SetuBusiness.cs:line 49

**Comment by GardenHamster** [comment]
https://github.com/GardenHamster/Theresa3rd-Bot/issues/22
